### ISSUE TITLE
rsGit fails to change branch

### ISSUE THREAD

**Issue by mkey0bc** [rsWinAutomationSupport/rsPackageSourceManager#14] opened 2015-09-09 12:23 UTC
After updating a branch in rsPlatform, rsGit does not change the branch of the resource to the new branch after DSC runs. rsPlatform is updated and copied over to C:\Program Files\WindowsPowerShell\Modules but the targeted resource is not updated.

**Comment by leshkinski** [comment] 2015-09-09 12:46
@mkey0bc Do you know if the branch change takes place on subsequent LCM runs or not?

**Comment by mkey0bc** [comment] 2015-09-09 12:50
I ran start-dscconfiguration -useexisting -verbose -wait -force 3 times with no luck. The only way I was able to get it to change branches was to delete the module from the server and run rsPullserver.ps1 directly.

**Comment by leshkinski** [comment] 2015-09-09 13:00
Ah, ok! I suspect that the cause of this may be one of the two below (I haven't fully investigated this to confirm yet):
- The '-useexisting' switch, will reapply the current.mof on the pull server, whcich will not contain the changes introduced into the most recent rsPlatform module. This can be confirmed by looking at the current.mof and seeing what it actually does in the rsGit code block for the affected module. So we may have to re-generate the current.mof by running rsPullServer.ps1 to take the latest branch configuration for use by LCM, and subsequently by PackageManager module
- Second, I had unexpected results with module/configuration updates not being processed due to PS module cache being out of date (old version of rsPlatform being in cache). The trick to avoiding that was to either run LCM in debug mode or by restarting the wmi processes in question (Get-Process wmi\* | Stop-Process -Force) 

Module update process on Pull servers is something we may need to investigate in more detail, but I'm not sure if it can be solved within PackageManager alone.

**Comment by mkey0bc** [comment] 2015-09-09 13:03
the rsplatform was replaced and moved to the modules directory so when DSC executed it was using the new rsPlatform.

**Comment by leshkinski** [comment] 2015-09-09 13:06
That's what I mean - even with the new rsPlatform module configuration code being in the modules directory, the local LCM process may not be picking it up due to the same module being cached, so the changes may not be making it to the resulting mof file.

We definitely need to investigate this further...

**Comment by leshkinski** [comment] 2015-09-09 13:09
Out of interest, has the module version of the rsPlatform module been bumped?

**Comment by leshkinski** [comment] 2015-10-02 08:24
hi @mkey0bc - did you have any further issues with this?

**Comment by leshkinski** [comment] 2015-11-09 11:56
Closing this issue - the process for DSC module upgrades/redeployment needs to be reviewed/changed from the current one as it currently requires too much manual intervention and multiple DSC config runs.

**Closed as completed by leshkinski** 2015-11-09 11:56 UTC
Labels: bug
